name: CI_teste
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  install-dependencies:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install
        working-directory: ./testeaulas
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Jest
        run: npm install jest
        working-directory: ./testeaulas
      - name: Run tests
        run: npm test
        working-directory: ./testeaulas
  run-prettier:
    name: Run prettier
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier
        working-directory: ./testeaulas
      - name: Run Prettier
        run: npx prettier . --write
        working-directory: ./testeaulas
